[tool.poetry]
name = "teams-support-bot"
version = "0.1.0"
description = "Microsoft Teams Support Bot"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.0"
gunicorn = "^23.0.0"
langchain-google-genai = "^2.1.1"
requests = "^2.32.0"
python-dotenv = "^1.1.0"
pyjwt = "^2.8.0"
cryptography = "^42.0.0"
uvicorn = "^0.29.0"
asgiref = "^3.8.0"
urllib3 = "^2.2.0"
google-generativeai = "^0.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"