# render.yaml
services:
  - type: web
    name: teams-support-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: PORT
        value: 5000